image_width: 640
image_height: 480
camera_name: usb_left
camera_matrix:
  rows: 3
  cols: 3
  data: [605.42208,   0.     , 343.35712,
           0.     , 610.62159, 255.37778,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.331231, 0.136627, 0.002541, -0.002604, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [544.92084,   0.     , 345.94431,   0.     ,
           0.     , 576.05634, 257.50223,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]