/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "usb_left_frame"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 640
      image_height: 480
      camera_name: "usb_left"
      camera_info_url: "package://usb_cam/config/usb_left/camera_info.yaml"
