image_width: 640
image_height: 480
camera_name: usb_front
camera_matrix:
  rows: 3
  cols: 3
  data: [593.82133,   0.     , 304.98768,
           0.     , 597.54283, 220.12715,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.354455, 0.236840, 0.003490, 0.000694, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [535.89441,   0.     , 302.47954,   0.     ,
           0.     , 562.47461, 218.66632,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]