image_width: 640
image_height: 480
camera_name: usb_right
camera_matrix:
  rows: 3
  cols: 3
  data: [365.09894,   0.     , 304.15607,
           0.     , 365.44256, 222.90177,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.270323, 0.063892, 0.001657, 0.004846, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [274.64487,   0.     , 305.92746,   0.     ,
           0.     , 315.03143, 217.88072,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]