image_width: 640
image_height: 480
camera_name: usb_back
camera_matrix:
  rows: 3
  cols: 3
  data: [607.26291,   0.     , 340.94449,
           0.     , 606.8915 , 241.14935,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.348074, 0.254346, 0.000580, 0.001358, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [552.52899,   0.     , 344.45255,   0.     ,
           0.     , 573.24493, 240.97214,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]