/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera2"
      pixel_format: "yuyv"
      color_format: "yuv422p"
      image_width: 640
      image_height: 360
      camera_name: "test_camera2"
      camera_info_url: "package://usb_cam/config/camera_info2.yaml"
