/armor_detector:
  ros__parameters:
  # Detector params.
    armor_type_wh_thres: 3
    # max_lost_cnt: 5
    max_armors_cnt: 8
    # max_v: 8
    max_delta_t: 100
    # no_crop_thres: 0.01
    # hero_danger_zone: 4
    color: true # red: true
                # blue: false
    # no_crop_ratio: 0.002
    # full_crop_ratio: 0.0001
    armor_roi_expand_ratio_width: 1.1
    armor_roi_expand_ratio_height: 1.5
    armor_conf_high_thres: 0.82

  # # Spinning params.
  #   anti_spin_judge_high_thres: 20000.0
  #   anti_spin_judge_low_thres: 2000.0
  #   anti_spin_max_r_multiple: 4.5
  #   max_dead_buffer: 2
  #   max_delta_dist: 0.5
  #   min_fitting_lens: 10
  #   shoot_delay: 50
  #   max_cost: 500
  #   switch_max_dt: 10000.0
    
    delta_x_3d_high_thresh: 0.18
    delta_x_3d_higher_thresh: 0.25
    delta_x_3d_low_thresh: 0.10
    delta_x_3d_lower_thresh: 0.05
    delta_y_3d_high_thresh: 0.18
    delta_y_3d_higher_thresh: 0.25
    delta_y_3d_low_thresh: 0.10
    delta_y_3d_lower_thresh: 0.05

  # Camera config params.
    # camera_name: "00J90630561" 
    camera_name: "KE0200110075" 
    camera_type: 3
    camera_param_path: "src/global_user/config/camera.yaml"

  # Network model path.
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-0127-001.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-0527-002.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/1106-333.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/yolox.xml"
    # network_path: "src/vehicle_system/autoaim/armor_detector/model/opt-1208-001.xml"
    network_path: "src/armor_detector/model/opt-0127-001.xml"
  
  # Data saving.
    # save_data: false
    # save_path: "src/data/infer2_5.txt"
    # save_dataset: false
  
  # Debug params.
    debug: true
    # using_imu: false
    # using_roi: false
    # draw_predict: true
    show_img: true
    show_fps: false
    # print_letency: false
    # print_target_info: false
    detect_red: true
    # disable_filter: false
    # disable_fitting: true
    # show_predict: false
    using_shared_memory: false
    show_transformed_info: false
    auto_label: false
    show_all_armors: false

